/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DailyReportsRouteImport } from './routes/daily-reports'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as BicyclePurchasesIndexRouteImport } from './routes/bicycle-purchases/index'
import { Route as BicyclePurchasesIdRouteImport } from './routes/bicycle-purchases/$id'
import { Route as BicyclePurchasesNewRouteImport } from './routes/bicycle-purchases/new'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as ExpensesNewRouteImport } from './routes/expenses/new'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as PurchaseInvoicesIndexRouteImport } from './routes/purchase-invoices/index'
import { Route as PurchaseInvoicesIdRouteImport } from './routes/purchase-invoices/$id'
import { Route as PurchaseInvoicesNewRouteImport } from './routes/purchase-invoices/new'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksIdRouteImport } from './routes/tasks/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportsRoute = DailyReportsRouteImport.update({
  id: '/daily-reports',
  path: '/daily-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BicyclePurchasesIndexRoute = BicyclePurchasesIndexRouteImport.update({
  id: '/bicycle-purchases/',
  path: '/bicycle-purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const BicyclePurchasesIdRoute = BicyclePurchasesIdRouteImport.update({
  id: '/bicycle-purchases/$id',
  path: '/bicycle-purchases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BicyclePurchasesNewRoute = BicyclePurchasesNewRouteImport.update({
  id: '/bicycle-purchases/new',
  path: '/bicycle-purchases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseInvoicesIndexRoute = PurchaseInvoicesIndexRouteImport.update({
  id: '/purchase-invoices/',
  path: '/purchase-invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseInvoicesIdRoute = PurchaseInvoicesIdRouteImport.update({
  id: '/purchase-invoices/$id',
  path: '/purchase-invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseInvoicesNewRoute = PurchaseInvoicesNewRouteImport.update({
  id: '/purchase-invoices/new',
  path: '/purchase-invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/daily-reports': typeof DailyReportsRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/exports': typeof ExportsRoute
  '/inventory': typeof InventoryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/bicycle-purchases/$id': typeof BicyclePurchasesIdRoute
  '/bicycle-purchases/new': typeof BicyclePurchasesNewRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/people/$id': typeof PeopleIdRoute
  '/purchase-invoices/$id': typeof PurchaseInvoicesIdRoute
  '/purchase-invoices/new': typeof PurchaseInvoicesNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/bicycle-purchases/': typeof BicyclePurchasesIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/purchase-invoices/': typeof PurchaseInvoicesIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/daily-reports': typeof DailyReportsRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/exports': typeof ExportsRoute
  '/inventory': typeof InventoryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/bicycle-purchases/$id': typeof BicyclePurchasesIdRoute
  '/bicycle-purchases/new': typeof BicyclePurchasesNewRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/people/$id': typeof PeopleIdRoute
  '/purchase-invoices/$id': typeof PurchaseInvoicesIdRoute
  '/purchase-invoices/new': typeof PurchaseInvoicesNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/bicycle-purchases': typeof BicyclePurchasesIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/people': typeof PeopleIndexRoute
  '/purchase-invoices': typeof PurchaseInvoicesIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/daily-reports': typeof DailyReportsRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/exports': typeof ExportsRoute
  '/inventory': typeof InventoryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/bicycle-purchases/$id': typeof BicyclePurchasesIdRoute
  '/bicycle-purchases/new': typeof BicyclePurchasesNewRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/people/$id': typeof PeopleIdRoute
  '/purchase-invoices/$id': typeof PurchaseInvoicesIdRoute
  '/purchase-invoices/new': typeof PurchaseInvoicesNewRoute
  '/tasks/$id': typeof TasksIdRoute
  '/bicycle-purchases/': typeof BicyclePurchasesIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/purchase-invoices/': typeof PurchaseInvoicesIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/audit'
    | '/daily-reports'
    | '/dashboard'
    | '/earnings'
    | '/exports'
    | '/inventory'
    | '/messages'
    | '/notifications'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/users'
    | '/bicycle-purchases/$id'
    | '/bicycle-purchases/new'
    | '/expenses/new'
    | '/people/$id'
    | '/purchase-invoices/$id'
    | '/purchase-invoices/new'
    | '/tasks/$id'
    | '/bicycle-purchases/'
    | '/expenses/'
    | '/people/'
    | '/purchase-invoices/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/audit'
    | '/daily-reports'
    | '/dashboard'
    | '/earnings'
    | '/exports'
    | '/inventory'
    | '/messages'
    | '/notifications'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/users'
    | '/bicycle-purchases/$id'
    | '/bicycle-purchases/new'
    | '/expenses/new'
    | '/people/$id'
    | '/purchase-invoices/$id'
    | '/purchase-invoices/new'
    | '/tasks/$id'
    | '/bicycle-purchases'
    | '/expenses'
    | '/people'
    | '/purchase-invoices'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/audit'
    | '/daily-reports'
    | '/dashboard'
    | '/earnings'
    | '/exports'
    | '/inventory'
    | '/messages'
    | '/notifications'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/users'
    | '/bicycle-purchases/$id'
    | '/bicycle-purchases/new'
    | '/expenses/new'
    | '/people/$id'
    | '/purchase-invoices/$id'
    | '/purchase-invoices/new'
    | '/tasks/$id'
    | '/bicycle-purchases/'
    | '/expenses/'
    | '/people/'
    | '/purchase-invoices/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  DailyReportsRoute: typeof DailyReportsRoute
  DashboardRoute: typeof DashboardRoute
  EarningsRoute: typeof EarningsRoute
  ExportsRoute: typeof ExportsRoute
  InventoryRoute: typeof InventoryRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PermissionsRoute: typeof PermissionsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  BicyclePurchasesIdRoute: typeof BicyclePurchasesIdRoute
  BicyclePurchasesNewRoute: typeof BicyclePurchasesNewRoute
  ExpensesNewRoute: typeof ExpensesNewRoute
  PeopleIdRoute: typeof PeopleIdRoute
  PurchaseInvoicesIdRoute: typeof PurchaseInvoicesIdRoute
  PurchaseInvoicesNewRoute: typeof PurchaseInvoicesNewRoute
  TasksIdRoute: typeof TasksIdRoute
  BicyclePurchasesIndexRoute: typeof BicyclePurchasesIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PurchaseInvoicesIndexRoute: typeof PurchaseInvoicesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-reports': {
      id: '/daily-reports'
      path: '/daily-reports'
      fullPath: '/daily-reports'
      preLoaderRoute: typeof DailyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bicycle-purchases/': {
      id: '/bicycle-purchases/'
      path: '/bicycle-purchases'
      fullPath: '/bicycle-purchases/'
      preLoaderRoute: typeof BicyclePurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bicycle-purchases/$id': {
      id: '/bicycle-purchases/$id'
      path: '/bicycle-purchases/$id'
      fullPath: '/bicycle-purchases/$id'
      preLoaderRoute: typeof BicyclePurchasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bicycle-purchases/new': {
      id: '/bicycle-purchases/new'
      path: '/bicycle-purchases/new'
      fullPath: '/bicycle-purchases/new'
      preLoaderRoute: typeof BicyclePurchasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-invoices/': {
      id: '/purchase-invoices/'
      path: '/purchase-invoices'
      fullPath: '/purchase-invoices/'
      preLoaderRoute: typeof PurchaseInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-invoices/$id': {
      id: '/purchase-invoices/$id'
      path: '/purchase-invoices/$id'
      fullPath: '/purchase-invoices/$id'
      preLoaderRoute: typeof PurchaseInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-invoices/new': {
      id: '/purchase-invoices/new'
      path: '/purchase-invoices/new'
      fullPath: '/purchase-invoices/new'
      preLoaderRoute: typeof PurchaseInvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  DailyReportsRoute: DailyReportsRoute,
  DashboardRoute: DashboardRoute,
  EarningsRoute: EarningsRoute,
  ExportsRoute: ExportsRoute,
  InventoryRoute: InventoryRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PermissionsRoute: PermissionsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  BicyclePurchasesIdRoute: BicyclePurchasesIdRoute,
  BicyclePurchasesNewRoute: BicyclePurchasesNewRoute,
  ExpensesNewRoute: ExpensesNewRoute,
  PeopleIdRoute: PeopleIdRoute,
  PurchaseInvoicesIdRoute: PurchaseInvoicesIdRoute,
  PurchaseInvoicesNewRoute: PurchaseInvoicesNewRoute,
  TasksIdRoute: TasksIdRoute,
  BicyclePurchasesIndexRoute: BicyclePurchasesIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PurchaseInvoicesIndexRoute: PurchaseInvoicesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
